[package]
org = "ballerinax"
name = "financial.iso20022"
version = "1.0.1"
distribution = "2201.10.1"
authors=["Ballerina"]
export=["financial.iso20022", "financial.iso20022.cash_management", "financial.iso20022.payment_initiation", "financial.iso20022.payments_clearing_and_settlement"]
keywords=["Financial", "ISO20022"]
repository="https://github.com/ballerina-platform/module-ballerinax-financial.iso20022"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true
